name: anka_fitness
description: "QR Prototype - Spor Salonu Üye Yönetim ve Giriş Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.8.1

  # QR Code
  qr_flutter: ^4.1.0

  # QR Scanner (Admin tarafı)
  mobile_scanner: ^7.0.1

  # Security (Dinamik QR hash)
  crypto: ^3.0.6

  # Localization & Formatting
  intl: ^0.19.0

  # Typography
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
