// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX_Frxe1BF-IVVdZyKlqDX-C6NXNxkBgo',
    appId: '1:104286011209:android:ff288a4242ba85e3c8a498',
    messagingSenderId: '104286011209',
    projectId: 'ankafitness-app-123',
    storageBucket: 'ankafitness-app-123.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkc9ZmxkGv9Ukbr7biYNWH-16_iTQkWvQ',
    appId: '1:104286011209:ios:107f3be0b6942e45c8a498',
    messagingSenderId: '104286011209',
    projectId: 'ankafitness-app-123',
    storageBucket: 'ankafitness-app-123.firebasestorage.app',
    iosBundleId: 'com.ankafitness.ankaFitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSYmUbifT_Zvb9nospNWNYCvqM2tOEto',
    appId: '1:104286011209:web:5df82506062c9fe5c8a498',
    messagingSenderId: '104286011209',
    projectId: 'ankafitness-app-123',
    authDomain: 'ankafitness-app-123.firebaseapp.com',
    storageBucket: 'ankafitness-app-123.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSYmUbifT_Zvb9nospNWNYCvqM2tOEto',
    appId: '1:104286011209:web:5df82506062c9fe5c8a498',
    messagingSenderId: '104286011209',
    projectId: 'ankafitness-app-123',
    authDomain: 'ankafitness-app-123.firebaseapp.com',
    storageBucket: 'ankafitness-app-123.firebasestorage.app',
  );
}
